services:
  backend:
    container_name: capuchin-server

    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-8080}:8080"
    volumes:
      - ./backend/db:/app/db
    restart: unless-stopped

  frontend:
    container_name: capuchin-client

    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-8000}:80"
    restart: unless-stopped
