services:
  backend:
    build:
      target: dev
    volumes:
      - ./backend:/app
    environment:
      - MODE=dev

  frontend:
    build:
      target: builder
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - "${CLIENT_PORT:-8000}:5173"
