-- Auto-generated schema snapshot. DO NOT EDIT MANUALLY.
-- Regenerated by the release pipeline after each successful goose migration run.
-- Used by Docker to bootstrap a fresh dev database container.
-- Source of truth for schema changes remains backend/migration/db/migrations/*.sql

CREATE TABLE IF NOT EXISTS users (
    id          UUID        PRIMARY KEY,
    email       TEXT        UNIQUE NOT NULL,
    password_hash TEXT      NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
    id          UUID        PRIMARY KEY,
    item        TEXT        NOT NULL,
    completed   BOOLEAN     NOT NULL DEFAULT FALSE,
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blacklisted_tokens (
    token       TEXT        PRIMARY KEY,
    expired_at  TIMESTAMPTZ NOT NULL
);
