-- Auto-generated schema snapshot. DO NOT EDIT MANUALLY.
-- Regenerated by CI after each successful goose migration run.
-- Dual purpose:
--   1. Used by Docker Compose to bootstrap a fresh local dev database container.
--   2. Referenced by migration integration tests (TestInitSQLMatchesMigrationEndState)
--      as the schema reference snapshot.
-- Source of truth for schema changes: backend/migration/db/migrations/*.sql

CREATE TABLE IF NOT EXISTS users (
    id          UUID        PRIMARY KEY,
    email       TEXT        UNIQUE NOT NULL,
    password_hash TEXT      NOT NULL
);

CREATE TABLE IF NOT EXISTS todos (
    id          UUID        PRIMARY KEY,
    item        TEXT        NOT NULL,
    completed   BOOLEAN     NOT NULL DEFAULT FALSE,
    user_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blacklisted_tokens (
    token       TEXT        PRIMARY KEY,
    expired_at  TIMESTAMPTZ NOT NULL
);
